### ISSUE TITLE
💡 Event object pooling in EventBuffer

### ISSUE THREAD

**Issue by chaosddp** [microsoft/maro#118]
## Summary

Add pooling support for EventBuffer.Event object.

## Motivation

Reduce memory allocation times.

## Description

Currently our EventBuffer will create a new event object when there is an requirement, and dispatch it to related handler at a certain time, then push it into finished pool for outside querying. But if the outside does not need this, then these memory will be wasted, and cannot be re-used.

With pooling support, we can re-use event object that the states is completed for further event request, saving lot of memory
 and allocation time. 

This feature will make get_finished_events method not work, maybe we can:

1. provide a switch to enable pooling, default is disabled.
2. provide another way that just dump finished events to files.

## References

No

## Alternatives

No

## Additional context

No

**Comment by ArthurJiang** [comment]
@chaosddp 
How about using a solution like the data loader, we keep a double buffer. When the quota of one event pool is used out, we use another thread to write it out and switch to another one, vice versa.

**Comment by chaosddp** [comment]
> @chaosddp
> How about using a solution like the data loader, we keep a double buffer. When the quota of one event pool is used out, we use another thread to write it out and switch to another one, vice versa.
> 
> And the finished events will get from disk + active polling (the working one).

Yes, but python GIL is the block, double buffer with thread may not have much improvement. Maybe we can have another sub-process that always start with main process, that used to collect information (event, log or others) that will cost too much IO related times. We can use multipleprocess.queue to implement this, and add a simple dispatcher to dispatch information to different part to process, such as save to file.
