### ISSUE TITLE
💡 Implementation of more RL algorithms

### ISSUE THREAD

**Issue by ysqyang** [microsoft/maro#129]
## Summary

Implementation of more RL algorithms.

## Motivation

The only out-of-the-box algorithm provided in v0.1 is the DQN algorithm, and it still leaves something to be desired as there is no support for various DQN variants such as dueling Q models and double DQN. We intend to add support to these features in v0.2. We also plan to provide implementations of more RL algorithms to make things easy for those who want to use pre-defined algorithms instead of writing their own from scratch.

## Description

More DQN features such as dueling and double DQN. Other classic RL algorithms such as PG, PPO, DDPG, A2C, A3C, etc.

## References

- Papers: 
PG: Reinforcement Learning: An Introduction (R. S. Sutton and A. Barto), 2nd ed., pp. 321
PPO: https://arxiv.org/pdf/1707.06347.pdf
DDPG: https://arxiv.org/pdf/1509.02971.pdf
A2C:  https://towardsdatascience.com/understanding-actor-critic-methods-931b97b6df3f
A3C: https://arxiv.org/pdf/1602.01783.pdf
- Implementations in other projects:
- Draft code snippets:

**Comment by ArthurJiang** [comment]
@ysqyang Please provide the planned algorithms list, the related reference, which will be implemented as p1.
