### ISSUE TITLE
💡 Add the field "ActionType" to the Action of CIM scenario

### ISSUE THREAD

**Issue by Jinyu-W** [microsoft/maro#145]
## Summary

Add the field ``ActionType`` to the ``Action`` of CIM scenario

## Motivation

An ``Action`` consists of an ``ActionType`` and a ``Quantity`` filed is much clearer.

## Description

Currently, the ``Action`` of CIM is a number, the detailed ActionType is presented by its sign. While the ``Action`` of Citi Bike is an object with both ``ActionType`` and ``Quantity``, which is much clearer than the previous one.

We can add a field of ``ActionType`` (valid values: Discharge, Load for now) for the CIM scenario to not only unify it with the Citi Bike scenario but also make it clearer.

**Comment by ArthurJiang** [comment]
Agree! @chaosddp

**Comment by Jinyu-W** [comment]
implemented in https://github.com/microsoft/maro/pull/266
