### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by ssfantasy** [microsoft/maro#260]
## Description

when I run the script of cim DQN example,  the pycharm show ImportError: cannot import name '__data_version__'

### Screenshots

![image](https://user-images.githubusercontent.com/37575229/105580061-10661c80-5dc5-11eb-8944-3d1dfd0cea9f.png)

## To Reproduce

1. 
2.
3.

## Expected Behavior

The example script was successfully run

## Environment

- MARO version (e.g., v0.01):
- PYMARO version (e.g., v0.2.0a1):
- MARO scenario (`CIM`):
- MARO component (`Simulation`, `RL`):
- How you installed MARO (`pip`):
- OS (`Windows`):
- Python version (`3.6`,):
- CPU:

**Comment by chaosddp** [comment]
@ssfantasy I cannot reproduce this within pycharm, would you please help to check if __data_version__ in maro/__misc__.py file?

**Comment by ssfantasy** [comment]
![image](https://user-images.githubusercontent.com/37575229/105800350-7a531180-5fd1-11eb-98fa-65e45578f7bd.png)

![image](https://user-images.githubusercontent.com/37575229/105800370-82ab4c80-5fd1-11eb-8e9b-3c8cc5c6072c.png)

**Comment by chaosddp** [comment]
It is real strange, maybe you are using venv for your python environment? @ssfantasy

**Comment by ssfantasy** [comment]
[packages.txt](https://github.com/microsoft/maro/files/5901818/packages.txt)

I create a enironment for maro，the version of my python is 3.6.5

**Comment by chaosddp** [comment]
How about use other environment manager, like conda? venv is not that stable, usually cause wired issues in my experiences.

**Comment by ssfantasy** [comment]
Which Python version required for PyMaro? 3.6? 3.7? 3.8?

**Comment by chaosddp** [comment]
3.6 and 3.7, not tested yet for other version.
