### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by Allen-labs** [microsoft/maro#264]
## Description

I have an error running the multi_process_launcher.py file in the maro/examples/cim/ dqn directory

### Screenshots

![image](https://user-images.githubusercontent.com/40318104/105955280-fff9be80-60b0-11eb-9a28-327e33a370f5.png)

## To Reproduce

python multi_process_launcher.py test_group 1

## Expected Behavior

No errors or warnings

## Environment

- MARO version (e.g., v0.1.1a1):0.2.0a1
- MARO scenario (`CIM`, `Citi Bike`):CIM
- MARO component (`Simulation`, `RL`, `Distributed Training`):
- Orchestration platform (`GraSS on Azure`, `AKS on Azure`):
- How you installed MARO (`pip`, `source`):pip
- OS (`Linux`, `Windows`, `macOS`):linux
- Python version (`3.6`, `3.7`):3.6
- Docker image (e.g., arthursjiang/maro:cpu[5f36ed]):
- CPU/GPU:CPU
- Any other relevant information:

**Comment by Jinyu-W** [comment]
Hi @Allen-labs , the bug fix(https://github.com/microsoft/maro/pull/265)  is merged into the master branch, please check it. Thanks!

**Comment by chaosddp** [comment]
Close since it was fixed, feel free to re-open it if there is any further comments.
