### ISSUE TITLE
how can we generate the topology dataset files based our own Virtual Machine Scheduling Scenario business？ Are there some examples or tools

### ISSUE THREAD

**Issue by yourmoonlight** [microsoft/maro#276]
from the docs, only find some Azure public datasets. 

if we want apply maro framework to our own scenario, IMHO, perhaps we should know how to generate our own dataset first？

**Comment by yourmoonlight** [comment]
@ArthurJiang @Jinyu-W @chaosddp @ysqyang

guys, any ideas?

**Comment by Jinyu-W** [comment]
@kyu-kuanwei Please help to answer this question. Add data scheme part in the doc if needed.

**Comment by Jinyu-W** [comment]
Thank you for your interest in this scenario and welcome to contribute new topologies! @yourmoonlight

**Comment by kyu-kuanwei** [comment]
@yourmoonlight  Sorry for our late reply. We just update the [Docs](https://maro.readthedocs.io/en/latest/scenarios/vm_scheduling.html#quick-start). 
Please check the data preparation part. We detailed the data schema and the data format that you can follow to prepare your own dataset.
And we also provided the `build` command to convert the csv files to the binary files that the MARO simulator can use. Please also see the Build Command part for detailed information.

Hope this helps and feel free to leave any comments.
