### ISSUE TITLE
🐛 I had an error executing "maro inspector geo --start database"

### ISSUE THREAD

**Issue by Allen-labs** [microsoft/maro#309]
## Description
I had an error executing "maro inspector geo --start database"

### Screenshots
<img width="844" alt="maro-real-time-vis" src="https://user-images.githubusercontent.com/40318104/112438585-08a20480-8d83-11eb-8dd6-1e7727607296.png">

## Environment

- MARO version : master branch
- MARO scenario (`CIM`, `Citi Bike`): cim
- MARO component (`Simulation`, `RL`, `Distributed Training`): maro_real_time_vis
- Orchestration platform (`GraSS on Azure`, `AKS on Azure`): vm on azure
- How you installed MARO (`pip`, `source`): source
- OS (`Linux`, `Windows`, `macOS`): centos
- Python version (`3.6`, `3.7`): 3.6
- Docker image (e.g., arthursjiang/maro:cpu[5f36ed]): 
- CPU/GPU: cpu

**Comment by Meroy9819** [comment]
Hello, it should be the problem of path splicing in different OS, which has now been resolved. You may pull branch master and try it again.

**Comment by Allen-labs** [comment]
thanks.
