### ISSUE TITLE
🐛 I had an error executing "maro inspector geo --start service..."

### ISSUE THREAD

**Issue by Allen-labs** [microsoft/maro#314]
I had an error executing "maro inspector geo --start service --experiment_name YOUR_EXPERIMENT_NAME --front_end_port 8080",  When building maro_vis_front_end, the dist folder does not exist

Screenshots
![image](https://user-images.githubusercontent.com/40318104/112973805-48eaf380-9184-11eb-98c6-28f0a3fdbbb5.png)

Environment
MARO version : master branch
MARO scenario (CIM, Citi Bike): cim
MARO component (Simulation, RL, Distributed Training): maro_real_time_vis
Orchestration platform (GraSS on Azure, AKS on Azure): vm on azure
How you installed MARO (pip, source): source
OS (Linux, Windows, macOS): centos
Python version (3.6, 3.7): 3.6
CPU/GPU: cpu

**Comment by Jinyu-W** [comment]
@Meroy9819  Could you help to figure it out?

**Comment by Meroy9819** [comment]
Hi, sorry for the late response. This error is because you did not install docker-compose. Please install it and try again.
Thanks!

**Comment by Ivens-Zhang** [comment]
@Meroy9819 
Hi, Thank you for your reply. I checked our remote server whether installed docker-compose. The terminal info is here:

![](https://gitee.com/zhangyi98/pictureBed/raw/master//img/3fcbcb56b71f4d276743a879a341948.png)

 So it may not caused by docker-compose. Our server use CentOS 7 System, and docker version is `20.10.2, build 2291f61`

**Comment by riccardopoiani** [comment]
Hello, same problem here with `docker-compose version 1.29.1, build c34c88b2` and `Docker version 20.10.6, build 370c289`.

Environment
MARO version : master branch
Orchestration platform (GraSS on Azure, AKS on Azure): none
How you installed MARO (pip, source): source
OS (Linux, Windows, macOS): Linux
Python version (3.6, 3.7): 3.7
CPU/GPU: cpu

**Comment by cpn** [comment]
Hello, I have the exact same problem with `Docker version 20.10.6` and `docker-compose version 1.29.1`.

**Comment by Meroy9819** [comment]
> Hello, I have the exact same problem with `Docker version 20.10.6` and `docker-compose version 1.29.1`.

Hi, the bug has been fixed, please pull the latest code and try again.

**Comment by riccardopoiani** [comment]
Hello @Meroy9819, I have now tried the latest code but when I run the query to retrieve exp id I obtain the following error:
`SELECT * FROM maro.experiments table does not exist [name=maro.experiments]`

**Comment by lihuoran** [comment]
Hi @riccardopoiani , we have made several modifications around Geo vis, and the bug you mentioned should already be fixed. Could you please pull the latest version (after commit [91cb60](https://github.com/microsoft/maro/commit/91cb603423f97cb173fd4d962c93735445e43625)) and try again? Thanks!

**Comment by riccardopoiani** [comment]
Hi @lihuoran , the previous error is fixed. However, I still have problems.
QuestDB successfuly retrieves the experiment from the table. However, when I start the inspector I am unable to visualize the data (in particular the problem arises as soon as I open the front end).

```
127.0.0.1 - - [02/Aug/2021 21:11:29] "POST /get_snapshot_port HTTP/1.1" 500 -
127.0.0.1 - - [02/Aug/2021 21:11:29] "OPTIONS /get_snapshot_vessel HTTP/1.1" 200 -
[2021-08-02 21:11:29,676] ERROR in app: Exception on /get_snapshot_vessel [POST]
Traceback (most recent call last):
  File "anaconda3/envs/marosourceok/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "anaconda3/envs/marosourceok/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "anaconda3/envs/marosourceok/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/anaconda3/envs/marosourceok/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "anaconda3/envs/marosourceok/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "anaconda3/envs/marosourceok/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "anaconda3/envs/marosourceok/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "maro/maro/cli/maro_real_time_vis/back_end/vis_app/app.py", line 80, in get_basic_vessel_info
    cur_experiment_name, cur_epoch_number, cur_snapshot_number
  File "maro/maro/cli/maro_real_time_vis/back_end/vis_app/data_process/request/request_vessel.py", line 37, in get_vessel_data
    return jsonify(process_vessel_data(db_vessel_data, tick))
  File "maro/maro/cli/maro_real_time_vis/back_end/vis_app/data_process/request/request_vessel.py", line 97, in process_vessel_data
    original_vessel_data = get_data_in_format(db_vessel_data)
  File "maro/maro/cli/maro_real_time_vis/back_end/vis_app/data_process/request/utils.py", line 17, in get_data_in_format
    dataset = original_data["dataset"]
KeyError: 'dataset'
```

The problem persists with the get of other elements as well.
In the end, no visualization happens.

**Comment by lihuoran** [comment]
@riccardopoiani Could you please provide your detailed instructions to reproduce this bug?

**Comment by lihuoran** [comment]
@riccardopoiani By the way, please try to delete your local `maro2020/geo_front_service` image and re-pull the latest one from the docker hub. This image has also been updated recently. See if this can help, thanks.

**Comment by riccardopoiani** [comment]
Hi @lihuoran I pulled the latest docker image from the docker hub and now things work just fine. 
Thanks :)
