### ISSUE TITLE
Visualization import error🐛 

### ISSUE THREAD

**Issue by cpn** [microsoft/maro#317]
## Description

Hello, I have just installed MARO using pypl, followed the quick example, but when running the visualization command `maro inspector dashboard --source_path ./dump_data/snapshot_dump_folder` I get the following error:
```
ModuleNotFoundError: No module named 'maro.cli.maro_real_time_vis.back_end'
```

## To Reproduce

1. Install MARO using pypl
2. Run the quick example
3. Run the visualization command `maro inspector dashboard --source_path ./dump_data/snapshot_dump_folder`

## Environment

- MARO version (e.g., v0.1.1a1): 0.2.1a1
- MARO scenario (`CIM`, `Citi Bike`): CIM
- MARO component (`Simulation`, `RL`, `Distributed Training`):
- Orchestration platform (`GraSS on Azure`, `AKS on Azure`):
- How you installed MARO (`pip`, `source`): pip
- OS (`Linux`, `Windows`, `macOS`): Linux
- Python version (`3.6`, `3.7`): 3.7
- Docker image (e.g., arthursjiang/maro:cpu[5f36ed]):
- CPU/GPU:
- Any other relevant information:

**Comment by Jinyu-W** [comment]
Hi @cpn , sorry for the late reply.

Currently the visualization part is not included in pymaro package, so you should install from source to use the viusalization.

**Comment by Jinyu-W** [comment]
Hi @cpn , could you please let us know if this solves your problem?

**Comment by ssviridov** [comment]
I have installed from source and have the same problem, seems like compiled dist for frontend was not committed.

**Comment by ershandreich** [comment]
@ssviridov Yeah, I have the same thing

**Comment by Ivens-Zhang** [comment]
Hi @Jinyu-W , I have the same problem, too. 😢

**Comment by Jinyu-W** [comment]
@Meroy9819  Could you help to check this problem?

**Comment by Jinyu-W** [comment]
@ssviridov  @ershandreich  @Ivens-Zhang I want to confirm that are you install MARO as: https://github.com/microsoft/maro#install-maro-from-source-editable-mode

**Comment by Ivens-Zhang** [comment]
Thanks for your prompt reply @Jinyu-W , I confirm that I was installed MARO as your link.

**Comment by Meroy9819** [comment]
> Thanks for your prompt reply @Jinyu-W , I confirm that I was installed MARO as your link.

@Ivens-Zhang 
Hi, I checked the startup process of Env-dashboard under Linux System, it works for me.  Actually, I am curious that the package maro_real_time_vis.back_end is imported within Env-dashboard startup process, if it is possible, could you please list the command and dump_data folder path in detail?

**Comment by cpn** [comment]
Hello, sorry about the late reply I was on holiday last week. I have tried installing it from source and now I get this error: `CliError: Manifest file missed.
`
It seems that this modification of the example script produces no file (the snapshot directory is empty):
```
from maro.simulator import Env
from maro.simulator.scenarios.cim.common import Action

env = Env(scenario="cim",
          topology="toy.5p_ssddd_l0.0",
          start_tick=0,
          durations=100,
          options={"enable-dump-snapshot": "./dump_data"})


metrics, decision_event, is_done = env.step(None)
action = Action(0, 0, 0, 0)

while not is_done:
    metrics, decision_event, is_done = env.step(action)

print(f"environment metrics: {env.metrics}")
```
The command I'm using is:
```  maro inspector dashboard --source_path ./dump_data/snapshot_dump_2021_04_12_15_42_21_159
```
The folder path is:
```
/home/ciprian/PycharmProjects/inventory_management/dump_data/snapshot_dump_2021_04_12_15_42_21_159
```

**Comment by ssviridov** [comment]
@Jinyu-W yes, I confirm that I installed from source.

**Comment by cpn** [comment]
It seems that using the quick start [example here](https://maro.readthedocs.io/en/latest/#quick-start) with the addition of the `options` parameter from above and the missing `action_type` parameter, the directory is filled now and I could use the visualization command. Thanks for the help!

**Comment by riccardopoiani** [comment]
To fix the code mentioned by @cpn one can also do the following: 

```
from maro.simulator import Env
from maro.simulator.scenarios.cim.common import Action

env = Env(scenario="cim",
          topology="toy.5p_ssddd_l0.0",
          start_tick=0,
          durations=100,
          options={"enable-dump-snapshot": "./dump_data"})
env.reset()

metrics, decision_event, is_done = env.step(None)
action = Action(0, 0, 0, 0)

while not is_done:
    metrics, decision_event, is_done = env.step(action)

print(f"environment metrics: {env.metrics}")
````

Indeed, `env.reset()` will call the code necessary to start the visualization process. Of course, when you will launch `maro inspector` an error will show for the intra-epoch visualization (since it is a single epoch). However, inter-epoch visualization works correctly.

**Comment by Meroy9819** [comment]
> To fix the code mentioned [here](https://github.com/microsoft/maro/issues/317#issuecomment-817826528) one might do the following:
> 
> ```
> from maro.simulator import Env
> from maro.simulator.scenarios.cim.common import Action
> 
> env = Env(scenario="cim",
>           topology="toy.5p_ssddd_l0.0",
>           start_tick=0,
>           durations=100,
>           options={"enable-dump-snapshot": "./dump_data"})
> env.reset()
> 
> metrics, decision_event, is_done = env.step(None)
> action = Action(0, 0, 0, 0)
> 
> while not is_done:
>     metrics, decision_event, is_done = env.step(action)
> 
> print(f"environment metrics: {env.metrics}")
> ```
> 
> Indeed, `env.reset()` will call the code necessary to start the visualization process. Of course, when you will launch `maro inspector` an error will show for the intra-epoch visualization (since it is a single epoch). However, inter-epoch visualization works correctly.

Thanks for your support! Your advice has been updated to the project.
