### ISSUE TITLE
🐛 Redis database not cleared when execution terminates

### ISSUE THREAD

**Issue by riccardopoiani** [microsoft/maro#327]
## Description

Redis database is not cleared once a running script is over.
If you run DQN example twice (using the same distributed group name), the second time you will get stuck at episode 0. Indeed, rollouts are sent to actor's IDs that were running at the first execution. Note that this won't happen if you stop the first execution.

I currently solved the problem using `redis-cli flushall`, however I categorize this as unexpected behavior since these informations should be cleaned when the execution terminates. 

## To Reproduce

1. Run `examples/cim/dqn/main.py` and wait till completion (you can change the episodes number to a small number e.g., 5 to speed up things)  
2. Run `examples/cim/dqn/main.py` 

## Expected Behavior
Redis cache should be cleared when the learning process ends. 

The second DQN execution should send rollouts to the actors that are currently running, and not the previous ones, that should not be stored in the redis database. 

## Environment

- MARO version (e.g., v0.1.1a1): master
- MARO scenario (`CIM`, `Citi Bike`): CIM
- MARO component (`Simulation`, `RL`, `Distributed Training`): Distributed Training
- Orchestration platform (`GraSS on Azure`, `AKS on Azure`): 
- How you installed MARO (`pip`, `source`): source
- OS (`Linux`, `Windows`, `macOS`): Linux
- Python version (`3.6`, `3.7`): 3.7
- Docker image (e.g., arthursjiang/maro:cpu[5f36ed]):
- CPU/GPU: cpu
- Any other relevant information:

**Comment by Jinyu-W** [comment]
Thanks for your report and the solution provided. We've added a close() function to clean the redis data in PR #335 to handle this problem.
