### ISSUE TITLE
Loosen dependencies?💡 

### ISSUE THREAD

**Issue by jreynolds01** [microsoft/maro#328]
## Summary

We would like to loosen the dependencies in the published package to be able to align with other projects that are on-going.

## Motivation

We would like to enable the use of this package in the context of several others with competing dependencies.

## References

N/A

## Alternatives

N/A

**Comment by Jinyu-W** [comment]
Some dependencies have already been loosened in #332.

Please tell us if you have further suggestions. Thank you!
