### ISSUE TITLE
The front end cannot retrieve data，when geo visualization is deployed on remote virtual machine🐛 

### ISSUE THREAD

**Issue by Allen-labs** [microsoft/maro#352]
## Description

When geo visualization is deployed on a remote virtual machine, the front end can't retrieve the data, probably because it can't adjust the IP address to get the data
### Screenshots
docker container
![image](https://user-images.githubusercontent.com/40318104/120591587-fa512280-c46e-11eb-8ba0-ca91938017d3.png)

geo vis
![image](https://user-images.githubusercontent.com/40318104/120591843-69c71200-c46f-11eb-9a80-06db3d6be4dc.png)

## To Reproduce

1.Start the database on remote vm
2.Start the front-end and back-end service on remote vm
3.Access Geo Vis from a remote address in a browser

## Environment

- MARO version (e.g., v0.1.1a1):0.2.2a3
- MARO scenario (`CIM`, `Citi Bike`):cim
- MARO component (`Simulation`, `RL`, `Distributed Training`):
- Orchestration platform (`GraSS on Azure`, `AKS on Azure`):
- How you installed MARO (`pip`, `source`):source
- OS (`Linux`, `Windows`, `macOS`):linux
- Python version (`3.6`, `3.7`):3.6
- Docker image (e.g., arthursjiang/maro:cpu[5f36ed]):
- CPU/GPU:cpu
- Any other relevant information:

**Comment by Jinyu-W** [comment]
@zhawan  Please help to figure it out.

**Comment by lihuoran** [comment]
Hi @Allen-labs , the bug you mentioned has been fixed (in commit [91cb60](https://github.com/microsoft/maro/commit/91cb603423f97cb173fd4d962c93735445e43625)). Please try again to see if it works as expected. Thanks!
