### ISSUE TITLE
On-policy training with multiple actors🐛 

### ISSUE THREAD

**Issue by riccardopoiani** [microsoft/maro#354]
## Description

When running On-policy with multiple actors, `ExperienceCollectionUtils.stack` will build a list containing in each element the results of  `CIMTrajectoryForAC.on_finish`. At this point, `OnPolicyLearner` will call `agent.learn` on each element of this list. 
However, `ActorCritic`, that requires on-policy data, will be on-policy only at the first iteration of this list. When data from the second actor are processed, the policy has already been updated multiple times (i.e., at the first iteration).

## To Reproduce

1. Modify `examples/ac/main.py` as in `examples/dqn/main.py` to run the code with multiple actors 

## Expected Behavior
Ideally, `ExperienceCollectionUtils.stack` should concatenate all the data collected from the different actors into a single dataset (for the single agent mode) or single dataset for each agent (for multi-agent mode) and then call the update a single time (or a single time for each agent). Indeed, the "references" advantages computed at the beginning of the learning process should remain fixed for the entire update. 
In other words, the following line of code from `ActorCritic`
```
state_values = self.model(states, task_name="critic").detach().squeeze()
return_est = get_lambda_returns(
    rewards, state_values, self.config.reward_discount, self.config.lam, k=self.config.k
)
advantages = return_est - state_values
```  
should be executed a single time at each iteration (or a single time for each agent). 

A more advanced `ActorCritic` implementation will specify an `sgd_batch_size` and will break the collected batch into mini-batch using random sampling at each training iteration.
It would also be interesting to specify a `global_batch_size`, so that actors will collect up to `global_batch_size` data to trigger an update (instead of having `learner_update_trigger`).  

## Environment

- MARO version (e.g., v0.1.1a1): master
- MARO scenario (`CIM`, `Citi Bike`): CIM
- MARO component (`Simulation`, `RL`, `Distributed Training`): RL
- Orchestration platform (`GraSS on Azure`, `AKS on Azure`): 
- How you installed MARO (`pip`, `source`): source
- OS (`Linux`, `Windows`, `macOS`): 
- Python version (`3.6`, `3.7`): 
- Docker image (e.g., arthursjiang/maro:cpu[5f36ed]):
- CPU/GPU: 
- Any other relevant information:

**Comment by ysqyang** [comment]
You are correct. Thanks for pointing out. Our new version has addressed this and will be rolled out in the near future.
