### ISSUE TITLE
Scheduler bug in SimpleMultiHeadModel 🐛 

### ISSUE THREAD

**Issue by riccardopoiani** [microsoft/maro#356]
## Description
When creating schedulers in `AbsCoreModel` a bug occur if `isinstance(optim_option, dict)` is True in the constructor.
This happens since while doing `self.scheduler[name] = opt.scheduler_cls(self.optimizer[name], **opt.scheduler_params)` since `self.scheduler` is not defined. 

## To Reproduce

1. Create a SimpleMultiHeadModel using a model with a dictionary and optim options that has schedulers.

## Expected Behavior

No crash should occurr.

## Environment

- MARO version (e.g., v0.1.1a1): master
- MARO scenario (`CIM`, `Citi Bike`): 
- MARO component (`Simulation`, `RL`, `Distributed Training`): RL
- Orchestration platform (`GraSS on Azure`, `AKS on Azure`):
- How you installed MARO (`pip`, `source`): source
- OS (`Linux`, `Windows`, `macOS`):
- Python version (`3.6`, `3.7`): 3.7
- Docker image (e.g., arthursjiang/maro:cpu[5f36ed]):
- CPU/GPU:
- Any other relevant information:

**Comment by ysqyang** [comment]
Fixed. Thanks for pointing it out.
