### ISSUE TITLE
Wrong prediction in future stop list in CIM scenario 🐛 

### ISSUE THREAD

**Issue by riccardopoiani** [microsoft/maro#360]
## Description
While estimating future vessel stops in `VesselFutureStopsPrediction` there is a bug in the starting point when`
last_loc_idx == next_loc_idx`. 

In particular, when the previous condition is satisfied, the predictions retrieved by `VesselFutureStopsPrediction._predict_future_stops()` are one step ahead. 

## To Reproduce

To reproduce the behavior, just run the following snippet of code.

```
from maro.backends.frame import SnapshotList
from maro.simulator import Env
from pprint import pprint
from typing import List
import numpy as np

# Initialize an Env for CIM scenario
env = Env(scenario="cim", topology="toy.4p_ssdd_l0.0", start_tick=0, durations=1120)
    
# Start the environment with None action
_, event, is_done = env.step(None)

while not is_done:
    metrics, event, is_done = env.step(None)

vessel_snapshots = env.snapshot_list["vessels"]
print(vessel_snapshots[[i for i in range(0, 20)]:2:['future_stop_list', 'future_stop_tick_list', 'last_loc_idx']].reshape(20, 7))
```

For `toy.4p_ssdd_l0.0` vessel arrivals happen every 7 steps. You can see that when at `t` such that `t % 7 == 0`, predictions will jump one step ahead. 

## Expected Behavior
When  `last_loc_idx == next_loc_idx` predictions should not be 1-step ahead. 

## Environment

- MARO version (e.g., v0.1.1a1): master
- MARO scenario (`CIM`, `Citi Bike`): CIM
- MARO component (`Simulation`, `RL`, `Distributed Training`): Simulation
- Orchestration platform (`GraSS on Azure`, `AKS on Azure`): 
- How you installed MARO (`pip`, `source`): source
- OS (`Linux`, `Windows`, `macOS`): Linux
- Python version (`3.6`, `3.7`): 3.7
- Docker image (e.g., arthursjiang/maro:cpu[5f36ed]):
- CPU/GPU:
- Any other relevant information:

**Comment by riccardopoiani** [comment]
I also noticed that a simular problem also holds for `VesselPastStopsWrapper`. 
In particular, while a vessel is parking at a port, it should still be present in the `past_stop_tick_list`. Otherwise,
recovering from snapshots 'concurrent' vessel arrivals at the same port requires some manipulations. 
Anyway, even from a conceptual point of view, I would expect that that recovering  `past_stop_tick_list` will also retrieve the current port in which the vessel is parked. Indeed, it has already stopped at that port. 

(to reproduce this behavior, just print `vessel_snapshots[[i for i in range(20, 35)]:2:['past_stop_tick_list']].reshape(15, 4)` at the end of the previous snippet)

**Comment by Jinyu-W** [comment]
Hi @riccardopoiani , thank you for this issue! We've fixed it in #363, you can pull the master branch and have a try. If you further met any problem, please let me know. :)

**Comment by riccardopoiani** [comment]
Hi @Jinyu-W, thank you very much for the fix. I have tried it now and future stops seems to work correctly. However, for the new implementation of past stops it seems kind of hard to retrieve from snapshots concurrent arrivals of vessels at the same port (something that seems to be very reasonable; in this way the agent can have a better view of the actions it should take, otherwise it would need to learn to infer this sort of information). A possible way now is to manipulate `future_stop_list` and `future_stop_tick_list` at the `event.tick - 1`, but it seems to be a bit "cumbersome".

As I was mentioning [here](https://github.com/microsoft/maro/issues/360#issuecomment-863029460), I would like to see this information as the last column of `past_stop_list` at the current tick.
Taking the previous example, `vessel_snapshots[[i for i in range(20, 35)]:2:['past_stop_tick_list']].reshape(15, 4) `, should output `[ 0.,  7., 14., 21.]` already from the second raw (i.e., tick `21`), since at tick `21 `the vessel stop happens.

If you do not like this sort of solution, an alternative, would be the one of inserting a new attribute in vessels so that we can retrieve its current port position (if it has parked somewhere).

**Comment by Jinyu-W** [comment]
Hi @riccardopoiani , may I know when will you need the current stop info? If you need it when you are going to take an action. I think you can get the port_idx from the corresponding pending decision event which the Env just throws out.

**Comment by riccardopoiani** [comment]
I need it in the trajectory, but I want to retrieve concurrent vessels at the same port, not the location of the current vessels.
Suppose that you an event at tick `7` that says that `vessel_idx=0` arrives at `port_idx=2`. And then, the next event is that, always at tick `7`, you have that `vessel_idx=3` arrives at `port_idx=2` as well. In this case, I would like to insert in the state of both events information on both vessels. 
To do that, when the first event is triggered, I need to retrieve the information that both vessels arrives at `port_idx=2` at tick `7`.

**Comment by riccardopoiani** [comment]
In other words, in `trajectory.get_state()`, I have a function like this (assuming to have on past_stop_list and past_stop_tick_list working in the way I was proposing):
```
    def _get_concurrent_arrival_at_port(self, vessel_snapshots, port_idx, tick, excluded_vessel_idx):
        arrivals = vessel_snapshots[tick::['past_stop_tick_list', 'past_stop_list']].reshape(self._num_vessels,
                                                                                             2 * self._past_stop_dim)
        arrivals = arrivals[:, [self._past_stop_dim - 1, 2 * self._past_stop_dim - 1]]
        vessels_at_port = np.argwhere(arrivals[:, 1] == port_idx).squeeze(1).astype('int')
        vessels_at_tick = np.argwhere(arrivals[:, 0] == tick).squeeze(1).astype('int')
        common = np.intersect1d(vessels_at_tick, vessels_at_port)
        to_keep_idxes = np.argwhere(common != excluded_vessel_idx).squeeze(1)
        return list(common[to_keep_idxes]), [tick for _ in common[to_keep_idxes]]
```
This computes all the vessels that, at a given tick, arrives at a given port.

**Comment by riccardopoiani** [comment]
If you like the idea I was proposing, it should work by moving the update , of past stops in `_on_arrival()` and changing vessel past stop wrapper in the following way:

```
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

from .entities import CimDataCollection


class VesselPastStopsWrapper:
    """Wrapper to get vessel past stops, it will be padding with None if stops number less than configured one.

    Examples:

        .. code-block:: python

            # Get past stops of vessel 0.
            stops = data_cntr.vessel_past_stops[0]
    """

    def __init__(self, data: CimDataCollection):
        self._stop_number = data.past_stop_number
        self._stops = data.vessels_stops

    def __getitem__(self, key):
        assert type(key) == tuple or type(key) == list
        assert len(key) == 3

        vessel_idx = key[0]
        last_loc_idx = key[1]
        next_loc_idx = key[2]

        # ignore current port if parking
        if last_loc_idx == next_loc_idx:
            next_loc_idx += 1

        # avoid negative index
        start = max(next_loc_idx - self._stop_number, 0)

        past_stop_list = self._stops[vessel_idx][start: next_loc_idx]

        # padding with None
        for _ in range(self._stop_number - len(past_stop_list)):
            past_stop_list.insert(0, None)

        return past_stop_list

```

**Comment by Jinyu-W** [comment]
Hi @riccardopoiani. It's a good idea to have the information where is the vessel, but I'm afraid it's not suitable to put this info in `past_stop_list` (does not match the meaning?). We'll add this information to the attribute of the vessel. And I'll let you know when it's ready.

**Comment by Jinyu-W** [comment]
Hi @riccardopoiani , we've added the parking port idx into the vessel  in PR #366, please check the master branch and try the attributes below:

```
        is_parking    # Is parking or not, 1 means parking, 0 means sailing.
        loc_port_idx  # The port index the vessel is parking at.
```

**Comment by riccardopoiani** [comment]
Hi @Jinyu-W thanks very much for the fix. Seems to be working to me :)

**Comment by riccardopoiani** [comment]
Hi @Jinyu-W I've found another strange behavior in future stop tick predictions.

The problem arises when there is noise in the vessel speed. To reproduce:

```
from maro.backends.frame import SnapshotList
from maro.simulator import Env
from pprint import pprint
from typing import List
import numpy as np

# Initialize an Env for CIM scenario
env = Env(scenario="cim", topology="global_trade.22p_l0.0", start_tick=0, durations=200)
    
# Start the environment with None action
_, event, is_done = env.step(None)

event_list_2 = []
while not is_done:
    event_list_2.append((event.port_idx, event.vessel_idx, event.tick))
    metrics, event, is_done = env.step(None)

vs = env.snapshot_list['vessels']
vs[100:[i for i in range(45)]:'future_stop_tick_list'].reshape(45, 3)
```

Here you can find that output that I had:

```
array([[ 92., 101., 134.],
       [ 94., 131., 159.],
       [121., 130., 171.],
       [108., 115., 148.],
       [ 83., 102., 130.],
       [116., 147., 153.],
       [109., 114., 137.],
       [ 87., 113., 139.],
       [116., 147., 158.],
       [113., 138., 147.],
       [102., 110., 120.],
       [127., 138., 192.],
       [ 98., 107., 150.],
       [109., 119., 127.],
       [145., 171., 182.],
       [ 68., 111., 132.],
       [124., 130., 158.],
       [121., 127., 158.],
       [100., 111., 136.],
       [ 83., 116., 126.],
       [134., 155., 191.],
       [129., 146., 175.],
       [107., 137., 147.],
       [129., 140., 181.],
       [102., 135., 144.],
       [ 48.,  72.,  87.],
       [ 83., 109., 125.],
       [ 98., 105., 126.],
       [106., 130., 136.],
       [ 97., 108., 117.],
       [109., 136., 173.],
       [ 81., 111., 152.],
       [ 98., 107., 118.],
       [128., 137., 142.],
       [108., 112., 178.],
       [101., 160., 164.],
       [108., 111., 170.],
       [140., 144., 210.],
       [159., 163., 237.],
       [119., 122., 181.],
       [109., 130., 160.],
       [ 88., 102., 111.],
       [102., 107., 134.],
       [ 75.,  88.,  96.],
       [ 98., 107., 113.]], dtype=float32)
```

As you can see, the current tick is `100`, and yet there are future vessel tick predictions that are way behind the current tick, for instance `[ 75.,  88.,  96.]`.

I would expect the snapshot to retrieve ticks that are always ahead of the current one.
