### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by slowy07** [microsoft/maro#378]
## Description
typo spelling grammar on ```microsoft/maro```

## To Reproduce

1. change to correct grammar with reference from [Miriam webster](https://www.merriam-webster.com/)

```bash
./tests/test_event_buffer.py:77: dispathing  ==> dispatching
./tests/test_event_buffer.py:145: folloing  ==> following
```

## Environment

- MARO version (e.g., v0.1.1a1):
- MARO scenario (`CIM`, `Citi Bike`):
- MARO component (`Simulation`, `RL`, `Distributed Training`):
- Orchestration platform (`GraSS on Azure`, `AKS on Azure`):
- How you installed MARO (`pip`, `source`): `20.0.2`
- OS (`Linux`, `Windows`, `macOS`): `linux arch`
- Python version (`3.6`, `3.7`):  `3.8`
- Docker image (e.g., maro2020/maro:latest):
- CPU/GPU: `amd ryzen 7 4800h/ gtx1650TI`
- Any other relevant information:

**Comment by Jinyu-W** [comment]
Thank you for your kind effort for this! Updated in #379
