### ISSUE TITLE
ImportError: cannot import name '__version__'🐛 

### ISSUE THREAD

**Issue by yangboz** [microsoft/maro#487]
## Description

while tring  Env visualization example code.

### Screenshots

(msmaro) apple@appledeMacBook-Pro msmaro % maro inspector dashboard --source_path ./dump_data/ 
Traceback (most recent call last):
  File "/Users/apple/miniconda3/envs/msmaro/bin/maro", line 5, in <module>
    from maro.cli.maro import main
  File "/Users/apple/miniconda3/envs/msmaro/lib/python3.6/site-packages/maro/cli/maro.py", line 11, in <module>
    from maro import __version__
ImportError: cannot import name '__version__'
(msmaro) apple@appledeMacBook-Pro msmaro % maro inspector dashboard --source_path ./dump_data/
Traceback (most recent call last):
  File "/Users/apple/miniconda3/envs/msmaro/bin/maro", line 5, in <module>
    from maro.cli.maro import main
  File "/Users/apple/miniconda3/envs/msmaro/lib/python3.6/site-packages/maro/cli/maro.py", line 11, in <module>
    from maro import __version__
ImportError: cannot import name '__version__'
(msmaro) apple@appledeMacBook-Pro msmaro % 

## To Reproduce

1.
2.
3.

## Expected Behavior

as example code works 

## Environment

- MARO version (e.g., v0.1.1a1):
- MARO scenario (`CIM`, `Citi Bike`):
- MARO component (`Simulation`, `RL`, `Distributed Training`):
- Orchestration platform (`GraSS on Azure`, `AKS on Azure`):
- How you installed MARO (`pip`, `source`):
- OS (`Linux`, `Windows`, `macOS`):
- Python version (`3.6`, `3.7`):
- Docker image (e.g., maro2020/maro:latest):
- CPU/GPU: CPU
- Any other relevant information:Macosx, py36+

**Comment by lihuoran** [comment]
Hi @yangboz , thank you for reporting this issue. Could please provide more details about how to reproduce this bug? For example, the way you install the MARO package and the complete code snippet.

**Comment by yangboz** [comment]
from  this link https://maro.readthedocs.io/en/latest/key_components/dashboard_visualization.html .
thanks.

**Comment by yangboz** [comment]
or try this commandline:

```
python maro/examples/hello_world/cim/hello_streamlit.py 

```
it will thrown: 

Traceback (most recent call last):
  File "maro/examples/hello_world/cim/hello_streamlit.py", line 6, in <module>
    from maro.simulator import Env
  File "/Users/apple/miniconda3/envs/msmaro/lib/python3.6/site-packages/maro/simulator/__init__.py", line 5, in <module>
    from .abs_core import AbsEnv, DecisionMode
  File "/Users/apple/miniconda3/envs/msmaro/lib/python3.6/site-packages/maro/simulator/abs_core.py", line 9, in <module>
    from maro.backends.frame import SnapshotList
  File "maro/backends/frame.pyx", line 24, in init maro.backends.frame
  File "/Users/apple/miniconda3/envs/msmaro/lib/python3.6/site-packages/maro/utils/__init__.py", line 5, in <module>
    from .utils import DottableDict, clone, convert_dottable, set_seeds
  File "/Users/apple/miniconda3/envs/msmaro/lib/python3.6/site-packages/maro/utils/utils.py", line 16, in <module>
    from maro import __data_version__
ImportError: cannot import name '__data_version__'
```

**Comment by yangboz** [comment]
or  try on this command
```
maro env data list
```

**Comment by lihuoran** [comment]
Both `maro env data list` and `python maro/examples/hello_world/cim/hello_streamlit.py` run normally on my device (Ubuntu 16.04) without raising any warning or error.
How did you install MARO on your device? Through `pip` or install from source?

**Comment by yangboz** [comment]
here is my local macosx env : Macosx 10.15.7 python3.6

and pip  list :Package                   Version
------------------------- -------------------
absl-py                   0.11.0
aiohttp                   3.8.1
aiosignal                 1.2.0
appdirs                   1.4.4
appnope                   0.1.2
argcomplete               1.12.2
argon2-cffi               20.1.0
astunparse                1.6.3
async-generator           1.10
async-timeout             4.0.2
attrs                     20.3.0
backcall                  0.2.0
beautifulsoup4            4.10.0
big-sleep                 0.7.0
bitstring                 3.1.7
black                     20.8b1
bleach                    3.3.0
boto3                     1.17.18
botocore                  1.20.18
box2d-py                  2.3.8
brotlipy                  0.7.0
bs4                       0.0.1
cachetools                4.2.1
capstone                  4.0.0rc1
certifi                   2020.6.20
cffi                      1.14.3
chardet                   4.0.0
charset-normalizer        2.0.8
click                     7.1.2
clikit                    0.6.2
cloudpickle               2.0.0
cmdstanpy                 0.9.5
colorama                  0.4.4
conda                     4.9.2
conda-package-handling    1.7.2
convertdate               2.3.2
crashtest                 0.3.1
cryptography              3.2.1
cycler                    0.11.0
Cython                    0.29.24
datamodel-code-generator  0.8.3
decorator                 4.4.2
defusedxml                0.7.1
Deprecated                1.2.13
ecdsa                     0.17.0
einops                    0.3.0
entrypoints               0.3
ephem                     4.1.1
esptool                   3.1
fastapi                   0.63.0
fastapi-code-generator    0.2.3
fire                      0.4.0
Flask                     2.0.2
flatbuffers               1.12
fonttools                 4.28.2
frozenlist                1.2.0
ftfy                      5.9
future                    0.18.2
gast                      0.3.3
genson                    1.2.2
google-auth               1.24.0
google-auth-oauthlib      0.4.2
google-pasta              0.2.0
gpt-2-simple              0.7.1
grpcio                    1.32.0
gunicorn                  20.0.4
gym                       0.23.1
gym-notices               0.0.6
h11                       0.12.0
h5py                      2.10.0
hijri-converter           2.2.2
holidays                  0.11.3.1
httpcore                  0.12.3
httpstan                  4.6.1
httpx                     0.17.1
idna                      2.10
importlib-metadata        4.11.3
inflect                   4.1.1
ipykernel                 5.5.0
ipython                   7.21.0
ipython-genutils          0.2.0
ipywidgets                7.6.3
isodate                   0.6.0
isort                     5.8.0
itsdangerous              2.0.1
jedi                      0.18.0
Jinja2                    2.11.0
jmespath                  0.10.0
jsonschema                3.2.0
jupyter                   1.0.0
jupyter-client            6.1.12
jupyter-console           6.3.0
jupyter-core              4.7.1
jupyterlab-pygments       0.1.2
jupyterlab-widgets        1.0.0
Keras-Preprocessing       1.1.2
kiwisolver                1.3.2
korean-lunar-calendar     0.2.1
langdetect                1.0.9
LunarCalendar             0.0.9
Markdown                  3.3.3
MarkupSafe                2.0.1
marshmallow               3.14.1
matplotlib                3.5.0
mistune                   0.8.4
msgpack-python            0.5.6
multidict                 5.2.0
mypy-extensions           0.4.3
nbclient                  0.5.3
nbconvert                 6.0.7
nbformat                  5.1.2
nest-asyncio              1.5.1
nose                      1.3.7
notebook                  6.3.0
numpy                     1.19.5
oauthlib                  3.1.0
openapi-schema-validator  0.1.5
openapi-spec-validator    0.2.10
opt-einsum                3.3.0
packaging                 20.9
pandas                    1.3.4
pandocfilters             1.4.3
parso                     0.8.1
pastel                    0.2.1
pathspec                  0.8.1
pefile                    2021.5.24
pexpect                   4.8.0
pickleshare               0.7.5
Pillow                    8.4.0
pip                       20.2.4
prance                    0.20.2
prometheus-client         0.9.0
prompt-toolkit            3.0.18
protobuf                  3.14.0
ptyprocess                0.7.0
pyasn1                    0.4.8
pyasn1-modules            0.2.8
pycosat                   0.6.3
pycparser                 2.20
pydantic                  1.8.1
pyelftools                0.27
Pygments                  2.8.1
pyhidapi                  0.0.2
pylev                     1.4.0
PyMeeus                   0.5.11
pyOpenSSL                 19.1.0
pyparsing                 2.4.7
pyrsistent                0.17.3
pyserial                  3.5
pysimdjson                3.2.0
PySnooper                 0.4.3
PySocks                   1.7.1
pystan                    3.3.0
python-dateutil           2.8.1
python-multipart          0.0.5
pytorch-pretrained-biggan 0.1.1
pytz                      2021.3
PyYAML                    5.4.1
pyzbar                    0.1.8
pyzmq                     22.0.3
qtconsole                 5.0.3
QtPy                      1.9.0
redis                     4.2.0
reedsolo                  1.5.4
regex                     2020.11.13
requests                  2.25.1
requests-oauthlib         1.3.0
rfc3986                   1.4.0
rsa                       4.7
ruamel-yaml               0.15.87
s3transfer                0.3.4
scipy                     1.4.1
semver                    2.13.0
Send2Trash                1.5.0
setuptools                50.3.1.post20201107
setuptools-git            1.2
setuptools-scm            6.3.2
shellingham               1.4.0
six                       1.15.0
sniffio                   1.2.0
soupsieve                 2.3.1
starlette                 0.13.6
stringcase                1.2.0
tensorboard               2.4.1
tensorboard-plugin-wit    1.8.0
tensorflow                2.2.0
tensorflow-cpu            2.4.1
tensorflow-estimator      2.4.0
termcolor                 1.1.0
terminado                 0.9.3
testpath                  0.4.4
toml                      0.10.2
tomli                     1.2.2
toposort                  1.6
torch                     1.7.1
torchvision               0.8.2
tornado                   6.1
tqdm                      4.51.0
traitlets                 5.0.5
typed-ast                 1.4.2
typer                     0.3.2
typing-extensions         3.7.4.3
urllib3                   1.25.11
uvicorn                   0.13.4
wcwidth                   0.2.5
webargs                   8.0.1
webencodings              0.5.1
Werkzeug                  2.0.2
wheel                     0.35.1
widgetsnbextension        3.5.1
wrapt                     1.12.1
yarl                      1.7.2
zipp                      3.7.0
I will try another clean pip  list only with pymaro  again.
and verified examples without visulaizaion.  works  inside  of  Docker playground .

**Comment by yangboz** [comment]
maybe I found the root cause of this issue, the __data_version__ already defined at "__misc__.py"
and manually fix the import from  __misc__ at  utils/utils.py ,and install from source works.
