### ISSUE TITLE
ModuleNotFoundError: No module named 'maro.cli.maro_real_time_vis.back_end.vis_app.data_process'🐛 

### ISSUE THREAD

**Issue by yangboz** [microsoft/maro#491]
## Description

a clean conda py37  activated ,then pip install pymaro, aria2p, tqdm
try example code as following:

```
maro inspector dashboard --source_path ./dump_data/
```

### Screenshots

o/cli/maro_real_time_vis/start_maro_geo_vis.py", line 13, in <module>
    from .back_end.vis_app.data_process.request.request_params import request_settings
ModuleNotFoundError: No module named 'maro.cli.maro_real_time_vis.back_end.vis_app.data_process'

## To Reproduce

pip list:

(py37msmaro) apple@appledeMacBook-Pro msmaro % pip list
Package               Version
--------------------- ---------
appdirs               1.4.4
aria2p                0.11.1
async-timeout         4.0.2
azure-common          1.1.28
azure-core            1.23.0
azure-storage-blob    12.8.1
azure-storage-common  2.1.0
bcrypt                3.2.0
cachetools            5.0.0
certifi               2021.10.8
cffi                  1.15.0
charset-normalizer    2.0.12
convertdate           2.4.0
cryptography          36.0.2
deepdiff              5.7.0
Deprecated            1.2.13
geographiclib         1.52
geopy                 2.2.0
google-auth           2.6.2
hijri-converter       2.2.3
holidays              0.13
idna                  3.3
importlib-metadata    4.11.3
isodate               0.6.1
korean-lunar-calendar 0.2.1
kubernetes            23.3.0
loguru                0.6.0
msrest                0.6.21
numpy                 1.19.5
oauthlib              3.2.0
ordered-set           4.0.2
packaging             21.3
pandas                1.1.5
paramiko              2.10.3
pip                   21.2.2
prompt-toolkit        3.0.28
psutil                5.8.0
pyaml                 21.10.1
pyasn1                0.4.8
pyasn1-modules        0.2.8
pycparser             2.21
pymaro                0.2.4a1
PyMeeus               0.5.11
PyNaCl                1.5.0
pyparsing             3.0.7
python-dateutil       2.8.2
pytz                  2022.1
PyYAML                5.4.1
pyzmq                 22.0.3
redis                 4.2.0
requests              2.26.0
requests-oauthlib     1.3.1
rsa                   4.8
setuptools            58.0.4
six                   1.16.0
stringcase            1.2.0
toml                  0.10.2
torch                 1.7.1
tqdm                  4.63.1
typing_extensions     4.1.1
urllib3               1.26.9
wcwidth               0.2.5
websocket-client      1.3.1
wheel                 0.37.1
wrapt                 1.14.0
zipp                  3.7.0
1.
2.
3.

## Environment

- MARO version (e.g., v0.1.1a1): https://maro.readthedocs.io/en/latest/
- MARO scenario (`CIM`, `Citi Bike`):
- MARO component (`Simulation`, `RL`, `Distributed Training`):
- Orchestration platform (`GraSS on Azure`, `AKS on Azure`):
- How you installed MARO (`pip`, `source`):
- OS (`Linux`, `Windows`, `macOS`):
- Python version (`3.7`):
- Docker image (e.g., pymaro):
- CPU/GPU:
- Any other relevant information:

## Additional Context

maybe related to  #487

**Comment by lihuoran** [comment]
Could please [install MARO from source](https://github.com/microsoft/maro/pull/490) and try again?

**Comment by yangboz** [comment]
this round I tried install from source. again it throws:
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Obtaining file:///Users/apple/Documents/msmaro/maro
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/Users/apple/Documents/msmaro/maro_venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/apple/Documents/msmaro/maro_venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/apple/Documents/msmaro/maro_venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/62/hrfn26914bxd9sq0k79xkjjh0000gn/T/pip-build-env-ioo0epjt/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/private/var/folders/62/hrfn26914bxd9sq0k79xkjjh0000gn/T/pip-build-env-ioo0epjt/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/62/hrfn26914bxd9sq0k79xkjjh0000gn/T/pip-build-env-ioo0epjt/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/62/hrfn26914bxd9sq0k79xkjjh0000gn/T/pip-build-env-ioo0epjt/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 16, in <module>
          from maro import __version__
        File "/Users/apple/Documents/msmaro/maro/maro/__init__.py", line 8, in <module>
          if not check_deployment_status():
        File "/Users/apple/Documents/msmaro/maro/maro/utils/utils.py", line 183, in check_deployment_status
          and version_info["MARO_DATA"]["version"] == __data_version__ \
      NameError: name '__data_version__' is not defined
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by lihuoran** [comment]
I still have some doubts that this is a problem with the environment configuration. In the traceback logs you provided above, we can see this instruction:
```
File "setup.py", line 16, in
from maro import version
```

However, the code in the original file ([link](https://github.com/microsoft/maro/blob/0973783e55ca07bf8e177910c9d47854117a4ea8/setup.py#L16)) shows this line should be `from maro import __version__`. Similar situation for [issue 487](https://github.com/microsoft/maro/issues/491).

Could you please have more further attempts from this point of view? For example, create a new Python virtual env, pull the latest MARO code on master branch, and install from source again?

**Comment by yangboz** [comment]
I did a pull request  #493 for  it, hope you guys review it ASAP.

**Comment by lihuoran** [comment]
> I did a pull request #493 for it, hope you guys review it ASAP.

We have already noticed [PR 493](https://github.com/microsoft/maro/pull/493) but it is better for us to clarify the real cause of this issue. `from maro import __data_version__` (the only modification in PR 493) runs just fine in our experiments so the problem doesn't seem to be caused by the code implementation. Again, could you please go through my comment above and we can have more discussions on that.

Thanks!

**Comment by yangboz** [comment]
> install MARO from source

used python 3.7 , it works now.
